import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { RED_COLOR } from '@/contants'
import Sidebar from './components/Sidebar'
import Topbar from './components/Topbar'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type Children = {
  children: ReactNode | ReactNode[]
}

const Layout: React.FC<Children> = ({ children }) => {
  return (
    <section className="w-full h-screen">
      <div className="flex h-full w-full">

        <div style={{
          backgroundColor: RED_COLOR
        }} className="lg:w-1/4 lg:block hidden h-full ">
          <Sidebar />
        </div>

        <div className="w-full ">
          <Topbar />

          <div className=" w-full h-screen p-4 bg-gray-100">
            {children}
          </div>
        </div>
      </div>
    </section>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
